"""add pengumuman table

Revision ID: 6ca1bdb02e1c
Revises: b772386d27f4
Create Date: 2025-07-13 23:52:50.322578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca1bdb02e1c'
down_revision: Union[str, Sequence[str], None] = 'b772386d27f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pengumuman', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('kelas', sa.String(), nullable=True),
    sa.Column('waktu_mulai', sa.String(), nullable=True),
    sa.Column('waktu_selesai', sa.String(), nullable=True),
    sa.Column('lokasi', sa.String(), nullable=True),
    sa.Column('fotoPengumuman', sa.String(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengumuman_id'), 'pengumuman', ['id'], unique=False)
    op.create_index(op.f('ix_pengumuman_nama_pengumuman'), 'pengumuman', ['nama_pengumuman'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pengumuman_nama_pengumuman'), table_name='pengumuman')
    op.drop_index(op.f('ix_pengumuman_id'), table_name='pengumuman')
    op.drop_table('pengumuman')
    # ### end Alembic commands ###
