"""Add kelas to kegiatan

Revision ID: b772386d27f4
Revises: 
Create Date: 2025-07-13 22:53:03.671537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b772386d27f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kegiatan', sa.Column('kelas', sa.String(), nullable=True))
    op.add_column('kegiatan', sa.Column('fotoKegiatan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kegiatan', 'fotoKegiatan')
    op.drop_column('kegiatan', 'kelas')
    # ### end Alembic commands ###
