"""Add student personal info fields

Revision ID: b79dbf1bffc3
Revises: 6ca1bdb02e1c
Create Date: 2025-07-23 01:55:47.327157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79dbf1bffc3'
down_revision: Union[str, Sequence[str], None] = '6ca1bdb02e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('tanggal_lahir', sa.String(), nullable=True))
    op.add_column('students', sa.Column('jenis_kelamin', sa.String(), nullable=True))
    op.add_column('students', sa.Column('no_hp', sa.String(), nullable=True))
    op.add_column('students', sa.Column('nama_orang_tua', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'nama_orang_tua')
    op.drop_column('students', 'no_hp')
    op.drop_column('students', 'jenis_kelamin')
    op.drop_column('students', 'tanggal_lahir')
    # ### end Alembic commands ###
